/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-08-01 20:54:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class newHeader_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1625919970058L));
    _jspx_dependants.put("jar:file:/C:/Users/user/Desktop/khbook/khbook/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/user/Desktop/khbook/khbook/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>문곰책방</title> \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/newHeader.css\">\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("\t<!-- jQuery library -->\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\t<!-- Popper JS -->\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("\t<!-- Latest compiled JavaScript -->\r\n");
      out.write("\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("     <div class=\"header-top\">\r\n");
      out.write("         <ul class=\"header-top-info1\">\r\n");
      out.write("        <!--\r\n");
      out.write("                <li class=\"store-info\"><a href=\"#\">매장안내 ▼</a></li>\r\n");
      out.write("                <div>    \r\n");
      out.write("                    <li><a href=\"#\">회원혜택 ▼</a></li>\r\n");
      out.write("                    <div class=\"benefit\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"header-top-info2\">\r\n");
      out.write("                <li class=\"login\"><a href=\"#\">로그인</a></li>\r\n");
      out.write("                <li><a href=\"#\">회원가입</a></li>\r\n");
      out.write("                <li><a href=\"#\">고객센터</a></li>\r\n");
      out.write("                <li><a href=\"#\">주문배송</a></li>\r\n");
      out.write("                <li><a href=\"#\"><img src=\"../components/image/baguni.svg\" style=\"width: 24px; height: 24px;\"></a></li>\r\n");
      out.write("        -->\r\n");
      out.write("            </ul> \r\n");
      out.write("    </div> \r\n");
      out.write("    <!--\r\n");
      out.write("        <div class=\"info\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">강남지원 1관 : 서울특별시 강남구 테헤란로14길 6 남도빌딩 2F, 3F, 4F, 5F, 6F</a></li>\r\n");
      out.write("                <li><a href=\"#\">강남지원 2관 : 서울특별시 강남구 테헤란로10길 9 그랑프리 빌딩 4F, 5F, 7F</a></li>\r\n");
      out.write("                <li><a href=\"#\">강남지원 3관 : 서울특별시 강남구 테헤란로 130 호산빌딩 5F, 6F</a></li>\r\n");
      out.write("                <li><a href=\"#\">종로지원 : 서울특별시 중구 남대문로 120 대일빌딩 2F, 3F</a></li>\r\n");
      out.write("                <li><a href=\"#\">당산지원 : 서울특별시 영등포구 선유동2로 57 이레빌딩 (구관) 19F, 20F</a></li>\r\n");
      out.write("                <li><a href=\"#\">이태원지원 : 서울특별시 용산구 보광로 73 한국폴리텍제1대학</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div> -->\r\n");
      out.write("    \r\n");
      out.write("        <div class=\"header-mid\">\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/common/mgbanner.png\" alt=\"\">\r\n");
      out.write("            <!-- <h1 class=\"logo\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                    <img src=\"../components/image/kh문고 로고 final.png\" style=\"width: 250px;\">\r\n");
      out.write("                </a> \r\n");
      out.write("            </h1>\r\n");
      out.write("            <div class=\"header-mid-searchBox\">\r\n");
      out.write("                <div class=\"flex\">\r\n");
      out.write("                <div class=\"searchBox-slideBox\">\r\n");
      out.write("                    <div class=\"searchBox-slideList\">\r\n");
      out.write("                        <div class=\"searchBox-slideContent\">\r\n");
      out.write("                                <a href=\"#\" class=\"fontColor\"><span >책번호1</span></a>\r\n");
      out.write("                                <a href=\"#\" class=\"fontColor\"><span>책번호2</span></a>\r\n");
      out.write("                                <a href=\"#\"  class=\"fontColor\"><span>책번호3</span></a>\r\n");
      out.write("                                <a href=\"#\"  class=\"fontColor\"><span >책번호4444444444</span></a>\r\n");
      out.write("                        </div>   \r\n");
      out.write("                        <div class=\"searchBox-slideContent\">\r\n");
      out.write("                                <a href=\"#\" class=\"fontColor\"><span class=\"text-deco\">책번호5</span></a>\r\n");
      out.write("                                <a href=\"#\" class=\"fontColor\"><span >책번호6</span></a>\r\n");
      out.write("                                <a href=\"#\" class=\"fontColor\"><span >책번호7</span></a>\r\n");
      out.write("                                <a href=\"#\" class=\"fontColor\"><span >책번호8</span></a>\r\n");
      out.write("                        </div>   \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"slide-pagination\"></div>\r\n");
      out.write("                <button class=\"searchBox-slideBtn-prev\"><</button>\r\n");
      out.write("                <button class=\"searchBox-slideBtn-next\">></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"flex searchBox-box\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <input type=\"text\" class=\"searchBox-input\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"searchBox-btn\" value=\"검색\">\r\n");
      out.write("                        <img src=\"../components/image/dotbo.png\" alt=\"\" \r\n");
      out.write("                        class=\"dotbo\">\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> -->\r\n");
      out.write("            <!-- 딱딱해 보이는 슬라이드  -->\r\n");
      out.write("            <!-- <div class=\"slide-box\">\r\n");
      out.write("                <div class=\"slide-list\">\r\n");
      out.write("                    <div class=\"slide-content\">\r\n");
      out.write("                        <a href=\"#\"><img src=\"../components/image/배너1.png\" alt=\"\"></a><span class=\"header-slide-explan\">책은 마음의 양식.</span>                   \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"slide-content\">\r\n");
      out.write("                        <a href=\"#\"><img src=\"../components/image/배너2.jpg\" alt=\"\"></a>\r\n");
      out.write("                        <span class=\"header-slide-explan\">양식은 언양식 불고기.</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"slide-content\">\r\n");
      out.write("                        <a href=\"#\"><img src=\"../components/image/캔들.jpg\" alt=\"\"></a>\r\n");
      out.write("                                <span class=\"header-slide-explan\">흰 배경 캔들 사세요.</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"slide-content\">\r\n");
      out.write("                        <a href=\"#\"><img src=\"../components/image/캔들2.jpg\" alt=\"\"></a>\r\n");
      out.write("                                <span class=\"header-slide-explan\">검은 배경 캔들 사세요.</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"flex slide-button\">\r\n");
      out.write("                <div class=\"slide-pagination\"></div>\r\n");
      out.write("                <button class=\"slide-button-prev\"><span><</span></button>\r\n");
      out.write("                <button class=\"slide-button-next\"><span>></span></button>\r\n");
      out.write("            </div>  -->\r\n");
      out.write("        </div>\r\n");
      out.write("  \r\n");
      out.write("    <div class=\"header-bottom\">\r\n");
      out.write("        <div class=\"header-bottom-div\">\r\n");
      out.write("            <!-- <div style=\"background-color: #353f67;\">\r\n");
      out.write("                <a href=\"#\"><img src=\"../components/image/작은삼선2.png\" alt=\"\" style=\"\r\n");
      out.write("                padding-top: 10px; \r\n");
      out.write("                padding-left: 10px; \r\n");
      out.write("                padding-right: 10px;\r\n");
      out.write("                \"></a>\r\n");
      out.write("            </div> -->\r\n");
      out.write("            <div class=\"header-menuBar1\">\r\n");
      out.write("                <ul class=\"flex\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                    \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/sellbookController/sellbook.do\"><div>문곰도서▼</div></a>\r\n");
      out.write("                     \t<ul class=\"eBook\">\r\n");
      out.write("                            <li><a href=\"#\">아동 도서</a></li>\r\n");
      out.write("                            <li><a href=\"#\">초등 도서</a></li>\r\n");
      out.write("                            <li><a href=\"#\">중등 도서</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                   <!--  <li><a href=\"#\">외국도서</a></li> -->\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ebook/pageEbook.do\"><div>문곰e북 ▼</div></a>\r\n");
      out.write("                        <ul class=\"eBook\">\r\n");
      out.write("                            <li><a href=\"#\">일반도서</a></li>\r\n");
      out.write("                            <li><a href=\"#\">판타지/무협</a></li>\r\n");
      out.write("                            <li><a href=\"#\">로맨스</a></li>\r\n");
      out.write("                            <li><a href=\"#\">코믹스</a></li>\r\n");
      out.write("                            <li><a href=\"#\">오디오북</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"item\">\r\n");
      out.write("                    \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/gift/giftView.do\">문곰템 ▼</a>\r\n");
      out.write("                    \t<ul class=\"giftTab\">\r\n");
      out.write("                            <li><a href='#'>전자기기</a></li>\r\n");
      out.write("                            <li><a href='#'>수납/정리</a></li>\r\n");
      out.write("                            <li><a href='#'>독서 필수템</a></li>\r\n");
      out.write("                            <li><a href=\"#\">잡화</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/usedboard/usedboardList.do\">중고</a></li>\r\n");
      out.write("                     <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/auction/auction.do\">경매</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"header-menuBar2\">\r\n");
      out.write("                <ul class=\"flex\">\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    <li><a href=\"#\">마이룸</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/adminPage.do\">관리자전용페이지</a></li>\r\n");
      out.write("                \t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/service/servicePage.do\">고객센터</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("    let item = $('.item');\r\n");
      out.write("    let tab = $('.giftTab');\r\n");
      out.write("    $(function(){\r\n");
      out.write("        $(item).mouseover(function(){\r\n");
      out.write("            // tab.slideDown(500);\r\n");
      out.write("            tab.css('display',\"flex\");   \r\n");
      out.write("            $(tab).mouseover(function(){\r\n");
      out.write("                tab.css('display',\"flex\"); \r\n");
      out.write("            })\r\n");
      out.write("        })\r\n");
      out.write("        $(tab).mouseout(function(){\r\n");
      out.write("            tab.css('display',\"none\");\r\n");
      out.write("        }) \r\n");
      out.write("        $(item).mouseout(function(){\r\n");
      out.write("            tab.css('display',\"none\");\r\n");
      out.write("        }) \r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/common/newHeader.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/common/newHeader.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/common/newHeader.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/common/newHeader.jsp(169,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember==null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                \t<li class=\"login\"><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/loginPage.do\">로그인</a></li>\r\n");
          out.write("                \t<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/enrollPage.do\">회원가입</a></li>\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/common/newHeader.jsp(173,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember!=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                \t<li class=\"user1\"><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/myroom.do\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.memberName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('님');
          out.write(' ');
          out.write('(');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.memberGradeNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(") ▽</a></li>\r\n");
          out.write("                \t");
          out.write("\r\n");
          out.write("                \t<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/logout.do\">로그아웃</a></li>\r\n");
          out.write("                \t\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
