/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-08-01 20:54:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class quickBar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1625919970058L));
    _jspx_dependants.put("jar:file:/C:/Users/user/Desktop/khbook/khbook/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/user/Desktop/khbook/khbook/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>quickBar</title>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("/* @import url(\"style.css\"); */\r\n");
      out.write("/* .qc-padding-left{\r\n");
      out.write("    padding-left: 18px;\r\n");
      out.write("} */\r\n");
      out.write(".quickContents{\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    left: 1700px;\r\n");
      out.write("    z-index: 5;\r\n");
      out.write("    /* min-width: 1350px; */\r\n");
      out.write("    width: 63px;\r\n");
      out.write("    height: 370px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-content: center;\r\n");
      out.write("}\r\n");
      out.write("/* .guide,.toSale{\r\n");
      out.write("    width: 61px;\r\n");
      out.write("    height: 114px;\r\n");
      out.write("    border: 1px solid silver;\r\n");
      out.write("} */\r\n");
      out.write(".topBtn,.botBtn{\r\n");
      out.write("    width: 63px;\r\n");
      out.write("    height: 36px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    border: 1px solid #AAB1C7;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    background-color: #FFFFFF;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-content: center;\r\n");
      out.write("}\r\n");
      out.write(".topBtn:hover,.botBtn:hover{\r\n");
      out.write("    border: 3px solid #AAB1C7;\r\n");
      out.write("}\r\n");
      out.write(".botBtn{\r\n");
      out.write("    margin-top: 2px;\r\n");
      out.write("    margin-bottom: 2px;\r\n");
      out.write("}\r\n");
      out.write("/* .openBar{\r\n");
      out.write("    background-color: #AAB1C7;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 63px;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("} */\r\n");
      out.write(".help{\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-content: center;\r\n");
      out.write("    width: 63px;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    padding: 12px 10px 12px 10px;\r\n");
      out.write("    border: 1px solid #AAB1C7;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write(".help img{\r\n");
      out.write("    width: 41px;\r\n");
      out.write("    height: 41px;\r\n");
      out.write("}\r\n");
      out.write(".help:hover{\r\n");
      out.write("    border: 3px solid #AAB1C7;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".chatting{\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-content: center;\r\n");
      out.write("    width: 63px;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    padding: 14px 10px 10px 10px;\r\n");
      out.write("    border: 2px solid #AAB1C7;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write(".chatting img{\r\n");
      out.write("    width: 41px;\r\n");
      out.write("    height: 41px;\r\n");
      out.write("}\r\n");
      out.write(".chatting:hover{\r\n");
      out.write("    border: 3px solid #AAB1C7;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".locationHome{\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-content: center;\r\n");
      out.write("    width: 63px;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    padding: 12px 10px 12px 10px;\r\n");
      out.write("    border: 2px solid #AAB1C7;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    margin-top: 2px;\r\n");
      out.write("}\r\n");
      out.write(".locationHome img{\r\n");
      out.write("    width: 41px;\r\n");
      out.write("    height: 41px;\r\n");
      out.write("}\r\n");
      out.write(".locationHome:hover{\r\n");
      out.write("    border: 3px solid #AAB1C7;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("/* .openBar img{\r\n");
      out.write("    width: 35px;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("}\r\n");
      out.write(".openBar-wrap{\r\n");
      out.write("    display: flex;\r\n");
      out.write("    width: 80px;\r\n");
      out.write("    margin-right: 30px;\r\n");
      out.write("}\r\n");
      out.write(".openBar-hover{\r\n");
      out.write("    width: 20px;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    margin-right: 2px;\r\n");
      out.write("    background-color: #AAB1C7;\r\n");
      out.write("    font-weight: 800;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("} */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"quickContents\">\r\n");
      out.write("        <div class=\"qc-padding-left\">\r\n");
      out.write("            <!-- <div>\r\n");
      out.write("            쇼핑가이드 \r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                    <img src=\"../components/image/쇼핑가이드.jpg\" alt=\"\" class=\"guide\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("            오늘만 특가 상품 \r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                    <img src=\"../components/image/오늘만특가_퀵.jpg\" alt=\"\" class=\"toSale\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </div> -->\r\n");
      out.write("            <button class=\"topBtn\" onclick=\"\">\r\n");
      out.write("            <!-- 최상단 이동 버튼 -->\r\n");
      out.write("            ▲\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"botBtn\" onclick=\"\">\r\n");
      out.write("            <!-- 최하단 이동 버튼 -->\r\n");
      out.write("            ▼\r\n");
      out.write("            </button>\r\n");
      out.write("            <!-- 상담문의, 관리자 연결 -->\r\n");
      out.write("                <button class=\"help\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/상담문의.png\" alt=\"상담문의\">\r\n");
      out.write("                </button>\r\n");
      out.write("                <button class=\"chatting\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/chatting.svg\" alt=\"채팅\">\r\n");
      out.write("                </button>\r\n");
      out.write("                <button class=\"locationHome\" onclick=\"location.assign('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/퀵바홈버튼.png\" alt=\"홈으로 이동\">\r\n");
      out.write("                </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- <div class=\"openBar-wrap\">\r\n");
      out.write("            <button class=\"openBar-hover\"> \r\n");
      out.write("                〈 \r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"openBar\">\r\n");
      out.write("                <img src=\"../components/image/최근본상품.svg\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> -->\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script>\r\n");
      out.write("    // var winWidth = $(\".quickContents\");\r\n");
      out.write("    // // console.log(winWidth);\r\n");
      out.write("    // // console.log(winWidth.css(\"left\"));\r\n");
      out.write("    // $(window).resize(function(){\r\n");
      out.write("    //     console.log($(window).width());\r\n");
      out.write("    //     if($(window).width()>1300){\r\n");
      out.write("    //         winWidth.css(\"left\",\"85%\");\r\n");
      out.write("    //     }else if($(window).width()<1300){\r\n");
      out.write("    //         winWidth.css(\"left\",\"130 0px\");\r\n");
      out.write("    //     }\r\n");
      out.write("    // })\r\n");
      out.write("    const topBtn = $(\".topBtn\");\r\n");
      out.write("    const botBtn = $(\".botBtn\");\r\n");
      out.write("    $(topBtn).click(function(){\r\n");
      out.write("        $('html, body').animate({scrollTop:'0'},800);\r\n");
      out.write("        // 상단 이동 버튼\r\n");
      out.write("    })\r\n");
      out.write("    $(botBtn).click(function(){\r\n");
      out.write("        //window.scrollTo(0,100000);\r\n");
      out.write("         let windowEnd = ($(document).height() - $(window).height());\r\n");
      out.write("        $('html, body').animate({scrollTop: windowEnd},800); \r\n");
      out.write("        // 하단 이동 버튼\r\n");
      out.write("    })\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/common/quickBar.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/common/quickBar.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/common/quickBar.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
